// ScenarioDefinitions — configuration for all 6 scenarios + 3 free aim focuses
export const FREE_AIM_CONFIGS = {
    flicking: {
        id: 'flicking',
        name: 'FLICKING',
        roomSize: { w: 30, h: 10, d: 30 },
        playerPos: [0, 1.7, 0],
        targetConfig: { radius: 0.5, speed: 0, lifetime: 2, movePattern: 'static' },
        spawnConfig: { maxActive: 1, spawnDelay: 0.3, spawnZone: 'wall_face' },
        gradeThresholds: { S: 90, A: 75, B: 55, C: 35 },
    },
    tracking: {
        id: 'tracking',
        name: 'TRACKING',
        roomSize: { w: 30, h: 10, d: 30 },
        playerPos: [0, 1.7, 0],
        targetConfig: { radius: 0.6, speed: 4, lifetime: Infinity, movePattern: 'strafe_sine', moveRange: 8 },
        spawnConfig: { maxActive: 2, spawnDelay: 0.5, spawnZone: 'wall_face' },
        gradeThresholds: { S: 85, A: 70, B: 50, C: 30 },
    },
    precision: {
        id: 'precision',
        name: 'PRECISION',
        roomSize: { w: 20, h: 8, d: 20 },
        playerPos: [0, 1.7, 5],
        targetConfig: { radius: 0.15, speed: 1, lifetime: 5, movePattern: 'drift' },
        spawnConfig: { maxActive: 3, spawnDelay: 1, spawnZone: 'wall_face' },
        gradeThresholds: { S: 80, A: 60, B: 40, C: 25 },
    },
};

export const SCENARIOS = {
    gridshot: {
        id: 'gridshot',
        name: 'GRIDSHOT',
        description: 'Rapid target elimination on a grid wall',
        duration: 60,
        roomSize: { w: 20, h: 8, d: 20 },
        playerPos: [0, 1.7, 8],
        targetConfig: { radius: 0.5, speed: 0, lifetime: 3, movePattern: 'static' },
        spawnConfig: { maxActive: 1, spawnDelay: 0, spawnZone: 'grid_wall', gridCols: 3, gridRows: 2 },
        gridWall: { cols: 3, rows: 2, wallZ: -10, wallW: 16, wallH: 5 },
        gradeThresholds: { S: 90, A: 75, B: 55, C: 35 },
    },
    strafeDuel: {
        id: 'strafeDuel',
        name: 'STRAFE DUEL',
        description: 'Track an enemy strafing left and right',
        duration: 60,
        roomSize: { w: 30, h: 8, d: 15 },
        playerPos: [0, 1.7, 5],
        targetConfig: { radius: 0.4, speed: 4, lifetime: Infinity, movePattern: 'strafe_sine', moveAxis: 'x', moveRange: 10 },
        spawnConfig: { maxActive: 1, spawnDelay: 0.5, spawnZone: 'center_lane' },
        gradeThresholds: { S: 85, A: 70, B: 50, C: 30 },
    },
    anglePeek: {
        id: 'anglePeek',
        name: 'ANGLE PEEK',
        description: 'React to enemies peeking from behind cover',
        duration: 90,
        roomSize: { w: 30, h: 8, d: 30 },
        playerPos: [0, 1.7, 10],
        targetConfig: { radius: 0.4, speed: 6, movePattern: 'peek', peekDuration: 1.2 },
        spawnConfig: { maxActive: 2, spawnDelay: 2, spawnZone: 'wall_face' },
        coverPositions: [
            { x: -8, z: -10, w: 2, h: 4, d: 1 },
            { x: 8, z: -10, w: 2, h: 4, d: 1 },
            { x: -8, z: -5, w: 2, h: 4, d: 1 },
            { x: 8, z: -5, w: 2, h: 4, d: 1 },
        ],
        gradeThresholds: { S: 80, A: 65, B: 45, C: 25 },
    },
    microAdjust: {
        id: 'microAdjust',
        name: 'MICRO ADJUST',
        description: 'Tiny targets with minimal movement',
        duration: 60,
        roomSize: { w: 20, h: 8, d: 20 },
        playerPos: [0, 1.7, 8],
        targetConfig: { radius: 0.15, speed: 1, lifetime: 5, movePattern: 'drift' },
        spawnConfig: { maxActive: 3, spawnDelay: 1, spawnZone: 'wall_face' },
        gradeThresholds: { S: 80, A: 60, B: 40, C: 25 },
    },
    flickShot: {
        id: 'flickShot',
        name: '180 FLICK',
        description: 'Targets spawn all around — spin and shoot',
        duration: 60,
        roomSize: { w: 25, h: 8, d: 25 },
        playerPos: [0, 1.7, 0],
        targetConfig: { radius: 0.5, speed: 0, lifetime: 2, movePattern: 'static' },
        spawnConfig: { maxActive: 1, spawnDelay: 0.5, spawnZone: 'full_360' },
        gradeThresholds: { S: 85, A: 70, B: 50, C: 30 },
    },
    multiTarget: {
        id: 'multiTarget',
        name: 'MULTI TARGET',
        description: 'Eliminate groups of enemies fast',
        duration: 90,
        roomSize: { w: 30, h: 8, d: 20 },
        playerPos: [0, 1.7, 8],
        targetConfig: { radius: 0.4, speed: 0, lifetime: 4, movePattern: 'static' },
        spawnConfig: { maxActive: 4, spawnDelay: 0.3, spawnZone: 'distributed' },
        gradeThresholds: { S: 88, A: 72, B: 52, C: 32 },
    },
};
